[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.5.0"
  NODE_ENV = "production"

# Handle API redirects in development mode
[[redirects]]
  from = "/api/*"
  to = "https://us-central1-ventryx-71b2a.cloudfunctions.net/api/:splat"
  status = 200
  force = true

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200