[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.9.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  # Tell Netlify to cache the node_modules folder to speed up builds
  CI = "false"

# Handle API redirects
[[redirects]]
  from = "/api/*"
  to = "https://us-central1-ventryx-71b2a.cloudfunctions.net/api/:splat"
  status = 200
  force = true

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200