[build]
  command = """
    echo 'Node version:' && node --version && 
    echo 'NPM version:' && npm --version && 
    npm ci && 
    npm list vite && 
    npm list @vitejs/plugin-react && 
    npm run build
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  # Tell Netlify to cache the node_modules folder to speed up builds
  CI = "false"

# Handle API redirects
[[redirects]]
  from = "/api/*"
  to = "https://us-central1-ventryx-71b2a.cloudfunctions.net/api/:splat"
  status = 200
  force = true

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200