[build]
  command = "npm run netlify:build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.9.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-optional"

# Explicitly ensure Vite is installed during build
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Pre-build steps to ensure dependencies are properly installed
[build.lifecycle]
  onBuild = "npm install vite@6.2.2 --save-dev"

# Handle API redirects in development mode
[[redirects]]
  from = "/api/*"
  to = "https://us-central1-ventryx-71b2a.cloudfunctions.net/api/:splat"
  status = 200
  force = true

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200